title = "rollup config"

[servers]
WriteEndpoint = [
  "http://hdmn1:4242",
  "http://hdmn3:4242"
]
ReadEndpoint  = [
  "http://hdmn2:4242"
]

[api]
SuggestMax    = "5000"
LookupLimit   = "500000"
LookupUseMeta = "true"
HoursPast     = -1
Batch         = 60
ReadWorkers   = 20
WriteWorkers  = 20

[metric]
List          = [
   'linux',
   'ntp',
   'os',
   'scollector',
   'tsd'
]
