title = "rollup config"

[servers]
WriteEndpoint = "http://arch3.lab5.defense.net:4242"
ReadEndpoint  = [
  "http://arch1.lab5.defense.net:4242",
  "http://arch4.lab5.defense.net:4242"
]

[api]
SuggestMax    = "3000"
LookupLimit   = "20000"
LookupUseMeta = "true"
HoursPast     = -1
Concurrency   = 10
Batch         = 70

[metric]
List = [
  "os"
  ]
