title = "rollup config"

[servers]
WriteEndpoint = [
  "http://tsdb1:4242"
]
ReadEndpoint  = [
  "http://tsdb2:4242",
]

[api]
SuggestMax    = "5000"
LookupLimit   = "1"
LookupUseMeta = "false"

[settings]
HoursPast     = -1
Batch         = 14
ReadWorkers   = 5
WriteWorkers  = 4
Interval      = "1h"
LogLevel      = 5

[rest]
Debug            = false
Timeout          = 2     # minutes
RetryCount       = 4
RetryWaitTime    = 2000   # milliseconds
RetryMaxWaitTime = 120    # seconds

[metric]
List          = [
'cpu',
]

