title = "rollup config"

[servers]
WriteEndpoint = "http://hdmn2.lon1.defense.net:4242"
ReadEndpoint  = [
  "http://hdmn2.lon1.defense.net:4243"
]

[api]
SuggestMax    = "5000"
LookupLimit   = "500000"
LookupUseMeta = "true"
HoursPast     = -24
Concurrency   = 40
Batch         = 35

[metric]
List = [
        'linux.'
  ]
